<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="4" total="8" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-10-10T18:46:18 IST" name="Suite" finished-at="2023-10-10T18:46:53 IST" duration-ms="34769">
    <groups>
    </groups>
    <test started-at="2023-10-10T18:46:18 IST" name="Test" finished-at="2023-10-10T18:46:53 IST" duration-ms="34769">
      <class name="tests.LoginTest">
        <test-method is-config="true" signature="setup()[pri:0, instance:tests.LoginTest@7ef82753]" started-at="2023-10-10T18:46:19 IST" name="setup" finished-at="2023-10-10T18:46:36 IST" duration-ms="17636" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="login()[pri:0, instance:tests.LoginTest@7ef82753]" started-at="2023-10-10T18:46:37 IST" name="login" finished-at="2023-10-10T18:46:40 IST" duration-ms="3066" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method signature="verifyTitle()[pri:0, instance:tests.LoginTest@7ef82753]" started-at="2023-10-10T18:46:40 IST" name="verifyTitle" finished-at="2023-10-10T18:46:40 IST" duration-ms="29" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyTitle -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:tests.LoginTest@7ef82753]" started-at="2023-10-10T18:46:51 IST" name="teardown" finished-at="2023-10-10T18:46:53 IST" duration-ms="2349" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- tests.LoginTest -->
      <class name="tests.HomePageTest">
        <test-method signature="clickTab()[pri:0, instance:tests.HomePageTest@7161d8d1]" started-at="2023-10-10T18:46:40 IST" name="clickTab" finished-at="2023-10-10T18:46:44 IST" duration-ms="4352" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clickTab -->
      </class> <!-- tests.HomePageTest -->
      <class name="tests.AddCustomerTest">
        <test-method signature="addCustomer()[pri:0, instance:tests.AddCustomerTest@5149d738]" started-at="2023-10-10T18:46:44 IST" name="addCustomer" finished-at="2023-10-10T18:46:50 IST" duration-ms="6217" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [asdf] but found [Customer Registered Successfully!!!]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [asdf] but found [Customer Registered Successfully!!!]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at tests.AddCustomerTest.addCustomer(AddCustomerTest.java:43)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addCustomer -->
      </class> <!-- tests.AddCustomerTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
